### ISSUE TITLE
How to extract from private pages

### ISSUE THREAD

**Issue by kzhk75** [kondoumh/sb2md#10]
Can we extract from private pages of Scrapbox?

**Comment by kondoumh** [comment]
You needs to set the cookie value to environment variables.

```shell
export SB_COOKIE_ID=connect.sid
export SB_COOKIE_VALUE=your_cookie
```

Cookie can be obtained using your browser's developer tools.

**Comment by kzhk75** [comment]
Thanks for your reply.

I'm using Developer Tools in chrome. 
Could you explain a bit more to get these cookie related in  Developer Tools?

**Comment by kondoumh** [comment]
Open the developer tools on the scrapbox site and select Application > Storage > Cookies > scrapbox.
You can get the cookie value by selecting the key name "connect.sid".

![](https://i.gyazo.com/575a49bb007d86afb6ae577b8ab5d02d.png)

**Comment by kzhk75** [comment]
Thank you.
It works with cookie strings.
